version: '3'
services:
    server:
        image: node
        container_name: server
        working_dir: /code
        ports:
            - 8000:8000
        volumes:
            - type: bind
              source: ./
              target: /code
        command: bash -c "npm install && npm run server"
        depends_on:
            - db
    db:
        image: postgres
        container_name: database
        environment:
            - POSTGRES_DB=social
            - POSTGRES_USER=tobikuyo
            - POSTGRES_PASSWORD=pass
        volumes:
            - 'data:/var/lib/postgresql/data'
            - './database:/docker-entrypoint-initdb.d/:ro'
volumes:
    data:
