version: '3'
services:
    server:
        image: node
        container_name: server
        working_dir: /code
        ports:
            - 8000:8000
        environment:
            - DB_NAME=social
            - DB_CONNECTION=mongodb://tobikuyo:pass@db:27017
        volumes:
            - type: bind
              source: ./
              target: /code
        command: bash -c "npm install && npm run server"
        depends_on:
            - db

    db:
        image: mongo
        container_name: database
        environment:
            - MONGO_INITDB_DATABASE=social
            - MONGO_INITDB_ROOT_USERNAME=tobikuyo
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - 'data:/var/lib/mongodb/data'
            - './database/seeds.js:/docker-entrypoint-initdb.d/social.js:ro'
volumes:
    data:
